### PR TITLE
Close #2 Create components for Status Lists

### LINKED ISSUE #2: Create components for Status Lists
We are in the process of moving some of our design work from Figma to react-storybooks so that it is:

1. Easier for developers to work quickly and iterate
2. Easier for designers and developers to work in tandem and provide functional feedback on each other's requirements and proposals.
3. We can continue moving toward a more standard library of components that can be used across Status, as well as by the wider community of DApp developers.

The second components we'd like built is the List (calls and headers) [here](https://www.figma.com/file/cb4p8AxLtTF3q1L6JYDnKN15/Index?node-id=0%3A1).

There will be a bounty for the issue after a little more discussion/clarification.

### PR DESCRIPTION
**Pull request by millnitzluan**
This PR close #2.

I have not created the exact same components as in Figma, instead of this, I've created examples on how to have the same result shown in Figma.

Bonus: I've add storybook-background, so we can change the background and can see the component with different background color, as we have some components in Figma with background white it's difficult to see with background page white too.

Fixed: I've fixed the checkbox color mentioned by @andytudhope.

### CODE REVIEW

**Comment by andytudhope** [comment]
Hi @millnitzluan! Nice work on the background.

1. Why is there a hand in the first cell item?
2. The spacing for the last 2 (i.t.o. how close to the right edge the arrow and badge are) seems wrong to me.
3. There is no item with a blue tick. 
4. Could you fix the merge conflicts?

**Comment by millnitzluan** [comment]
**1. Why is there a hand in the first cell item?**
 That's a icon that can be sent as props, like in figma. The component that have a title with icon.
**2. The spacing for the last 2 (i.t.o. how close to the right edge the arrow and badge are) seems wrong to me.**
 Fixed with styles in secondComponent props.
**3. There is no item with a blue tick.**
 Fixed, just created a example with secondComponent props
**4. Could you fix the merge conflicts?**
Yep, doing.

**Comment by millnitzluan** [comment]
@andytudhope All fixed, you can check it at https://millnitzluan.github.io/storybook

**Comment by millnitzluan** [comment]
@andytudhope, news about this PR?

**Pull request merged**
