### PR TITLE
Created Text Field component

### PR DESCRIPTION
**Pull request by vespertines**

### CODE REVIEW

**Comment by andytudhope** [comment]
Hey @vespertines! Thanks for this and welcome to the Status repos ❤️ 

What was the context for this - i.e. why would you like to see it included in our component library? Do you have a personal need for it? (I'm genuinely curious - we're trying to gather some feedback about what developers really need from component libraries).

**Comment by NicoEchoDelta** [comment]
> Hey @vespertines! Thanks for this and welcome to the Status repos ❤️
> 
> What was the context for this - i.e. why would you like to see it included in our component library? Do you have a personal need for it? (I'm genuinely curious - we're trying to gather some feedback about what developers really need from component libraries).

Andy, I believe this was one tasks that Diana / PeopleOps had set from candidates.

**Comment by andytudhope** [comment]
Ok, that still doesn't provide me with any insight into what the actual goal of the PR is though?

@vespertines 

1. Why are the upgrades in `package.json` necessary?
2. We use the font Inter-UI across our product, it would seem important to use that rather than including material-ui base themes. You can find that font here: https://github.com/status-im/status.im/tree/develop/themes/navy/source/fonts
3. Can you clarify what the goal of this PR is?

**Comment by vespertines** [comment]
Sorry, @andytudhope I just noticed your comments.

1. I upgraded packapge.json for auditing package dependencies for security vulnerabilities.
2. Yes, surely we can add the font Inter-UI, but I found all other components were used material-ui only as the base style.
3. It's a starting point for adding Text Field component to Status Storybook. Temporary I used material-ui like other Status components but actual Status styling should be added in the future.

**Comment by andytudhope** [comment]
Cool @vespertines - would you please fix the merge conflicts here? And, if you could update the PR to use Inter-UI that'd be great. You can find the typography and other design elements like the colour palette which have yet to be included here: https://www.figma.com/file/cb4p8AxLtTF3q1L6JYDnKN15/Index?node-id=714%3A818

**Pull request closed without merging**
