### PR TITLE
Close #5 Create Component for Status Bottom Sheet

### LINKED ISSUE #5: Create Component for Status Bottom Sheet
We are in the process of moving some of our design work from Figma to react-storybooks so that it is:

1. Easier for developers to work quickly and iterate
2. Easier for designers and developers to work in tandem and provide functional feedback on each other's requirements and proposals.
3. We can continue moving toward a more standard library of components that can be used across Status, as well as by the wider community of DApp developers.

The fifth components we'd like built is the bottom sheet [here](https://www.figma.com/file/cb4p8AxLtTF3q1L6JYDnKN15/Index?node-id=0%3A1).

There will be a bounty for the issue after a little more discussion/clarification.

### PR DESCRIPTION
**Pull request by millnitzluan**
Hey I've created components to close PR #5 

buttons

### CODE REVIEW

**Comment by millnitzluan** [comment]
@bgits The example do you prefer like this? or you want to import BottomSheet example and only show the parameters that the component receive?

**Comment by bgits** [comment]
Using the bottomsheet example is fine. However the buttons in the example do not match the designs. It may require creating a `<RoundButton />` component.

**Comment by millnitzluan** [comment]
Oh, I thought that the component send as child to the bottomsheet is whatever, but okay, I'll create it

**Comment by millnitzluan** [comment]
@bgits Can you check it again? It would be nice if the designer should create a pallete of colors for the storybook, it will help in the development :D

**Comment by millnitzluan** [comment]
https://millnitzluan.github.io/storybook/

**Comment by andytudhope** [comment]
This lgtm - wdyt @bgits?

**Comment by bgits** [comment]
Comments from the designers:
1) original design component has circles under icons.

2) the production component should animate in from below the screen along the Y axis, not with alpha dissolve like it does now :slightly_smiling_face: I’m using it here in this Framer prototype, just click the (+) button https://framer.cloud/RAxDT

additional comments: also is our intention for the component to come with the actions already included inside or should they rather be added as children components ? because each of those buttons there is a `Button Bar` component itself, wouldn’t it be better to keep it separately ?

**Comment by millnitzluan** [comment]
I've made the  changes required, can you check it again? https://millnitzluan.github.io/storybook/

>additional comments: also is our intention for the component to come with the actions already included inside or should they rather be added as children components ? because each of those buttons there is a Button Bar component itself, wouldn’t it be better to keep it separately ?
>
Well, for BottomSheet component you can add customized components, like buttons or other components, something like this:
```
<BottomSheet>
  <CustomComponent />
</BottomSheet>
```
or with BottomSheetItem
```
<BottomSheet>
  <BottomSheetItem handleOnClick={function} icon={<SomeIcon />} content="SomeText" />
</BottomSheet>
```

**Comment by bgits** [comment]
> I've made the changes required, can you check it again? https://millnitzluan.github.io/storybook/
> 
> > additional comments: also is our intention for the component to come with the actions already included inside or should they rather be added as children components ? because each of those buttons there is a Button Bar component itself, wouldn’t it be better to keep it separately ?
> 
> Well, for BottomSheet component you can add customized components, like buttons or other components, something like this:
> 
> ```
> <BottomSheet>
>   <CustomComponent />
> </BottomSheet>
> ```
> or with BottomSheetItem
> 
> ```
> <BottomSheet>
>   <BottomSheetItem handleOnClick={function} icon={<SomeIcon />} content="SomeText" />
> </BottomSheet>
> ```

@denis-sharypin @errorist thoughts?

**Comment by millnitzluan** [comment]
@bgits I'm just waiting to close this PR to start working on Issue #4

**Comment by errorists** [comment]
Ok cool, so I'll comment on the bottom sheet alone and not the buttons. The correct animation curve for the dark background should be 200ms `cubic-bezier(0.4, 0.0, 0.2, 1)` and for the bottom sheet 300ms `cubic-bezier(0.0, 0.0, 0.2, 1)` when it appears and 250ms `cubic-bezier(0.4, 0.0, 1, 1)` when disappearing. Also it should have a 8px padding from the top and bottom to give some margin to children elements and probably some method to account for iPhone X safe area which is 34px high.

**Comment by errorists** [comment]
> What is the principle(s) behind the animation curve? Why is 200ms correct as opposed to 250ms, 300ms, etc?

In general, you choose the animation duration based on the distance the animation needs to traverse, so things moving across half of your screen need a longer duration than those that only nudge a bit. Often it requires trial and error and experience to get 'right'. 300ms is considered long, 200ms is average and the 100-150 range is short. For complex motion involving a lot of moving elements at once, an even longer duration like 500ms may be required.

Animation curves are chosen based on what happens with the element: 
- if it enters your view - you start with fast motion and ease it out at the end, 
- if an element already exists on the screen and animates to a different state, you both ease the beginning and the end
- if an element disappears from the view, you ease in only the beginning.

Elements which are directly manipulated with your touch like scrolling, swiping, use the spring physics model for motion.

**Comment by bgits** [comment]
> > What is the principle(s) behind the animation curve? Why is 200ms correct as opposed to 250ms, 300ms, etc?
> 
> In general, you choose the animation duration based on the distance the animation needs to traverse, so things moving across half of your screen need a longer duration than those that only nudge a bit. Often it requires trial and error and experience to get 'right'. 300ms is considered long, 200ms is average and the 100-150 range is short. For complex motion involving a lot of moving elements at once, an even longer duration like 500ms may be required.
> 
> Animation curves are chosen based on what happens with the element:
> 
> * if it enters your view - you start with fast motion and ease it out at the end,
> * if an element already exists on the screen and animates to a different state, you both ease the beginning and the end
> * if an element disappears from the view, you ease in only the beginning.
> 
> Elements which are directly manipulated with your touch like scrolling, swiping, use the spring physics model for motion.

Thanks. It seems defaults close to the ones described above are implemented in the library here: https://github.com/mui-org/material-ui/blob/master/packages/material-ui/src/styles/transitions.js#L20-L34 - please let us know if there is objection to these defaults for motion duration?

@millnitzluan if there is not any objection, perhaps we should use the `<Drawer />`  component which already implements these defaults via the <Slide /> component.

**Comment by millnitzluan** [comment]
@bgits I've implemented the drawer :)

**Comment by StatusSceptre** [comment]
@bgits @errorists wdyt now? Can we merge and pay here?

**Comment by bgits** [comment]
> @bgits @errorists wdyt now? Can we merge and pay here?

LGTM

**Comment by millnitzluan** [comment]
@bgits and @andytudhope news about this?

**Comment by andytudhope** [comment]
I can't merge, but would if I could @bgits. @errorists is OOO today, but perhaps he can take a quick look tomorrow so we can clear this?

**Comment by bgits** [comment]
@andytudhope merged

**Comment by andytudhope** [comment]
Hey @millnitzluan ❤️ So Barry has merged and I have paid out the bounty. I also sent you a "Collaboration Machine" kudos as our way of apologising for the delay... Also, please see this discuss post about what we're planning to do in the future (it's super exciting) and let me know if you'd like to get involved there. We will also be putting up bounties etc., so whichever ways works best for you 😉 

https://discuss.status.im/t/community-design-system/721/6

**Pull request merged**
