### PR TITLE
Close #4 - Create Components for Status Accessories, Inputs and tooltips

### LINKED ISSUE #4: Create Components for Status Accessories, Inputs and tooltips
We are in the process of moving some of our design work from Figma to react-storybooks so that it is:

1. Easier for developers to work quickly and iterate
2. Easier for designers and developers to work in tandem and provide functional feedback on each other's requirements and proposals.
3. We can continue moving toward a more standard library of components that can be used across Status, as well as by the wider community of DApp developers.

The fourth components we'd like built are the accessories, inputs and tooltips [here](https://www.figma.com/file/cb4p8AxLtTF3q1L6JYDnKN15/Index?node-id=0%3A1).

There will be a bounty for the issue after a little more discussion/clarification.

### PR DESCRIPTION
**Pull request by millnitzluan**
This pr close issue #4 
https://millnitzluan.github.io/storybook/

### CODE REVIEW

**Comment by bgits** [comment]
The PR needs to have merge conflicts resolved and can a demo storybook with these changes be published @millnitzluan ?

**Comment by millnitzluan** [comment]
Yep, this is tagged as WIP yet, I forget to solve some merge problems yet

**Comment by millnitzluan** [comment]
@bgits  and @StatusSceptre you can check this at https://millnitzluan.github.io/storybook :D

**Comment by bgits** [comment]
We have a component that can wrap components for display in storybook that will center them in the page. See `DesktopButton` can you please use it and fix the merge conflict.

**Comment by millnitzluan** [comment]
Sure, I'll do it

**Comment by millnitzluan** [comment]
@bgits Done! There's no conflict with master.
Hey, can I config eslint on this repo?

**Comment by millnitzluan** [comment]
@StatusSceptre news about this?

**Comment by StatusSceptre** [comment]
Hey @millnitzluan - 

1. There is a weird hover effect happening on the `Badge` and 
2. The `Switch` component doesn't switch on click (though it does register the event, and it does switch via the knobs - which could be the desired behaviour, still catching up here 😅)

**Comment by millnitzluan** [comment]
@StatusSceptre I fixed the shadow, for me the switch button is creating the event, and if you check the switch on knobs it'll switch to true or false.

**Comment by StatusSceptre** [comment]
Sorry, one more thing: I think we should cap the badge value to `9+` which is the current implementation in the app. There are discussions on the go about doing away with this, but it will likely require updating the badge as a whole, so let's stick with what is in the app right now for the moment.

**Comment by bgits** [comment]
please also fix conflicts, github shows this pr being in conflict with master

**Comment by millnitzluan** [comment]
@bgits To me is showing that `This branch has no conflicts with the base branch`

**Comment by bgits** [comment]
Seems order related as it can be merged, but not rebased. Ok, let it be.

**Comment by millnitzluan** [comment]
@bgits Maybe it's only showing to you, because to me it's up to update.

**Comment by millnitzluan** [comment]
If this well cause some problems please ping me

**Pull request merged**
